### ISSUE TITLE
ZInvalidRequest when registering images

### ISSUE THREAD

**Issue by weathermon83** [deepskystacker/DSS#126] opened 2020-10-22 21:28 UTC
Hi all, when registering subs on the new 4.2.5, it's throwing an exception (never did it on 4.2.3).  

![image](https://user-images.githubusercontent.com/73315657/96931838-4a433080-1501-11eb-9285-e300195ab5d0.png)

**Comment by perdrix52** [comment] 2020-10-23 10:20
Thank you for reporting this.  Please could I ask you to post about it on the support mailing list [as](https://groups.io/g/DeepSkyStacker/) well so folks know it is (now) a known problem.

Drats! I thought I had fixed all those problems.

It's a bit of a pain for me to switch back to the 4.2.5 build environment (different compiler etc. etc.).

However if you can make a few images available for testing on (e.g.) Dropbox, or Google Drive or whatever I will try to find a spare day or several to work on fixing this.   I'm pretty certain I know exactly what the problem is and why it is happening, the time cost isn't to fix the problem (I'm pretty sure what the problem is), it's to revert back the 4.2.5 build environment, and then afterwards to restore the 5.1 environment.  Hmmm maybe I can find the space on one of the other computers to set up a parallel build environment for 4.2.5 - it will require a bit of work to release the space, but probably well worth the effort.

David

**Comment by perdrix52** [comment] 2020-10-23 12:00
Additionally please include the filelist file so I can use the exact same options you did to create the problem... 

I'm guessing that you are using Super Pixel mode.   Every time I fix the code for that in one place, it seems to break in another!

David

**Comment by grndvl1** [comment] 2020-11-28 18:54
Just got this error when adding stars to a frame.  Happened when I went to save it or when it autosaves when you move to another frame
![image](https://user-images.githubusercontent.com/739862/100523802-d687e980-3178-11eb-8e4a-d52ea83eb807.png)

**Comment by perdrix52** [comment] 2020-11-28 21:36
That directory is where the source file is on MY computer.   Were you by any chance using super-pixel mode?

Can you make the relevant image files available for debugging (Google drive/Dropbox/w.h.y.)?

Are you using 4.2.5?

**Comment by grndvl1** [comment] 2020-11-29 00:33
Sorry not sure what you mean by super pixel mode.  I use mostly all the defaults but I can save the settings and send put that into dropbox folder

**Comment by perdrix52** [comment] 2020-11-29 03:27
If you save the file-list (File/Save the File List) that will save all the settings and also how you used the files.

Super-pixel mode if you go to Settings/Raw/FITS DDP Settings... you will see that option there (and whether it is set).

**Comment by grndvl1** [comment] 2020-11-29 19:40
No was not using super pixel mode.  I think I saved the file list.  I tried it again and was not able to get the error. When I did get this error it was the second stacking I did.  I did a previous one with a different nebula.  I cleared the list and added the nebula and ran this one when I got it.

**Comment by icvalyssa** [comment] 2021-02-28 15:42
I am able to replicate this error.

**Comment by perdrix52** [comment] 2021-02-28 15:55
Please try turning off de-bloom

**Comment by transginger** [comment] 2021-03-17 10:05
For what it's worth, I was having this issue and turning off De-Bloom resolved it. Thanks!

**Comment by perdrix52** [comment] 2021-03-17 13:57
Yes, it’s a known problem now fixed but not yet released.

**Closed** 2022-11-04 14:04 UTC
